### 获取所有服务实例
GET http://localhost:8484/findAll?service=com.prayerlaputa.mobius.UserService

### 注册一个实例
POST http://localhost:8484/reg?service=com.prayerlaputa.mobius.UserService
Content-Type: application/json

{
  "context": "mobius-rpc",
  "host": "127.0.0.1",
  "port": 8081,
  "scheme": "http",
  "status": false,
  "parameters": {
    "env": "dev",
    "tag": "RED"
  }
}


### 取消注册一个实例
POST http://localhost:8484/unreg?service=com.prayerlaputa.mobius.UserService
Content-Type: application/json

{
  "context": "kkrpc",
  "host": "127.0.0.1",
  "port": 8081,
  "scheme": "http"
}